services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - micro_network

  # MongoDB
  mymongodb:
    image: mongo:7.0
    container_name: mymongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - micro_network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - order
      - product
    networks:
      - micro_network
    environment:
      - MONGODB_AUTH_URI=${MONGODB_AUTH_URI}
      - MONGODB_ORDER_URI=${MONGODB_ORDER_URI}
      - MONGODB_PRODUCT_URI=${MONGODB_PRODUCT_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}

  # Auth Service
  auth:
    build:
      context: ./auth
    container_name: auth
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - micro_network
    environment:
      - MONGODB_AUTH_URI=${MONGODB_AUTH_URI}
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_URI=${RABBITMQ_URI}

  # Product Service
  product:
    build:
      context: ./product
    container_name: product
    depends_on:
      - mymongodb
      - rabbitmq
      - auth
    ports:
      - "3001:3001"
    networks:
      - micro_network
    environment:
      - MONGODB_PRODUCT_URI=${MONGODB_PRODUCT_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}

  # Order Service
  order:
    build:
      context: ./order
    container_name: order
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3002:3002"
    networks:
      - micro_network
    environment:
      - MONGODB_ORDER_URI=${MONGODB_ORDER_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
    command: sh -c "sleep 5 && npm start"

volumes:
  mongo_data:


networks:
  micro_network:
    driver: bridge
